[[main]]
  name = "Writing"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Talks"
  pageRef = "talks"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Series"
  pageRef = "series"
  weight = 20
